# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/af98cc9a-83b7-4887-bff4-8f1999300b8c";
      fsType = "btrfs";
      options = [ "subvol=@nix/@" "rw" "ssd" "compress=zstd:1" "discard=async" "space_cache=v2"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/af98cc9a-83b7-4887-bff4-8f1999300b8c";
      fsType = "btrfs";
      options = [ "subvol=@nix/@nix" "rw" "ssd" "compress=zstd:1" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/af98cc9a-83b7-4887-bff4-8f1999300b8c";
      fsType = "btrfs";
      options = [ "subvol=@swap" "rw" "ssd" "discard=async" "space_cache=v2" "nodatacow" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/af98cc9a-83b7-4887-bff4-8f1999300b8c";
      fsType = "btrfs";
      options = [ "subvol=@home" "rw" "ssd" "compress=zstd:1" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/af98cc9a-83b7-4887-bff4-8f1999300b8c";
      fsType = "btrfs";
      options = [ "subvol=@nix/@etc_nixos" "rw" "ssd" "compress=zstd:1" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4AFA-0249";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot/nix" = {
    # depends = [
    #   "/boot"
    # ];
    device = "/boot/nix";
    fsType = "none";
    options = [
      "bind"
    ];
  };

  swapDevices = [{
    device = "/swap/swapfile";
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
